### PR TITLE
Update font sizings and spacing

### PR DESCRIPTION
**Pull request by joshdarby**
## Changes

This pull request makes the following changes:

- Reduces font sizes and spacing on the embed page 

In content:
Screen Shot 2019-12-19 at 12 47 03 PM

Footer:
Screen Shot 2019-12-19 at 12 46 03 PM

Sidebar:
Screen Shot 2019-12-19 at 12 48 36 PM

## Why

For #127

## Testing/Questions

Features that this PR affects:

- Embed feed template

Questions that need to be answered before merging:

- [ ] Is this PR targeting the correct branch in this repository?

### CODE REVIEW

**Comment by kaylima** [comment]
Thanks, @joshdarby! let's reduce the spacing between the byline and title by roughly 1/3 and also make the categories smaller: smaller font (let's do same as byline size) and shave off the padding on the top and bottom a bit so the overall orange part is less tall/takes up less space. we want the first thing your eye to see to be the Title, not the button. (we may want to change to a different color from the orange as well, I'll ask @MirandaEcho about this.)

**Comment by kaylima** [comment]
@joshdarby also, for the footer version:

- Can we stack the logo and "learn more and bring it closer to the stories?
- "stories from this project" still needs to be brought down closer to the stories and either centered above them or left aligned with the first story.

Screen Shot 2019-12-19 at 1 26 31 PM

**Comment by kaylima** [comment]
Actually, let's remove "learn more" and just make the logo clickable to wherever "learn more" was going to go... (if that's possible) @joshdarby

**Comment by joshdarby** [comment]
@kaylima https://github.com/INN/umbrella-inndev/pull/135/commits/5ec09c2336a0ba93c92a76ea0d08e36e3102e1af updates the embed with these changes:

- Reduces text spacing by 1/3 (between title, byline, and descriptions)
- Reduces top/bottom padding on the category button by half
- Removes "Learn More" link and instead links the logo
- Aligns "Stories from this project" with the first saved link

Homepage and footer:
screencapture-amplify-inndev-test-2019-12-19-17_15_41

Sidebar:
Screen Shot 2019-12-19 at 5 15 34 PM

**Pull request merged**
