### PR TITLE
Gabe largo touchups

### PR DESCRIPTION
**Pull request by gabehong**
## Changes

- Support page now styled for consistency with Largo Project homepage, with changes made to margins, padding, width, button styles.

- Copy now replaces Lorem ipsum text for User Guides and Help Desk sections

- User guides content divs now centered

### CODE REVIEW

**Comment by benlk** [comment]
Should the top of the support page have this grey background?

screen shot 2017-02-10 at 1 33 13 pm

**Comment by benlk** [comment]
screen shot 2017-02-10 at 1 41 42 pm

Also, these boxes need to be made a little taller so the text doesn't droop off at 650px.

**Comment by gabehong** [comment]
support page should have a grey background

gotcha, will change box size and commit

**Comment by benlk** [comment]
Ah, okay. It doesn't go all the way to the top on desktops, or all the way down to the footer:

screen shot 2017-02-10 at 2 10 06 pm

**Comment by gabehong** [comment]
Ah, I mean the Self-Help section (Knowledge Base + User Guides) should be gray, but the other sections are supposed to be white. 

Changed box size in latest commit

**Comment by benlk** [comment]
Are we worried about the white bar atop "Self Help"? 
screen shot 2017-02-10 at 3 04 03 pm

It's from the page padding, but we might want to make that grey.

**Pull request merged**
